/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.text.DecimalFormat;
import java.util.Random;

public class Library {

    public int[] roll(int n) {
        Random rand = new Random();
        int[] results = new int[n];

        for (int i = 0; i < n; i++) {
            int diceRoll = rand.nextInt(6) + 1;
            results[i] = diceRoll;
        }
        return results;
    }

    public boolean containsDuplicates(int[] arr) {
        for (int i = 0; i < arr.length - 1; i++) {
            for (int j = i + 1; j < arr.length; j++) {
                if (arr[i] == arr[j]) {
                    return true;
                }
            }
        }
        return false;
    }

    public double average(int[] arr) {
        int total = 0;
        for (int i = 0; i < arr.length; i++) {
            total = total + arr[i];
        }
        double average = (double) total / arr.length;
        DecimalFormat df = new DecimalFormat("#.##");
        String formatedString = df.format(average);
        return Double.parseDouble(formatedString);

    }

    public int[] lowestAverage(int[][] Arrays) {
        double minAverage = Double.MAX_VALUE;
        int[] lowArray = Arrays[0];
        for (int i = 0; i < Arrays.length; i++) {
            double sum = 0;
            for (int j = 0; j < Arrays[i].length; j++) {
                sum += Arrays[i][j];
            }
            double currentAverage = sum / Arrays[i].length;
            if (currentAverage < minAverage) {
                minAverage = currentAverage;
                lowArray = Arrays[i];
            }
        }
        return lowArray;
    }
}