/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}

class WeatherAnalyzerTest {
    public static void main(String[] args) {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        String[] expectedOutput = new String[]{"High: 72" + "Low: 51" + "Never saw temperature: 63" + "Never saw temperature: 67" + "Never saw temperature: 68" + "Never saw temperature: 69"};

        String actualOutput = WeatherAnalyzer.analyzeWeatherData(weeklyMonthTemperatures);

        if (expectedOutput.equals(actualOutput)) {
            System.out.println("Test passed!");
        } else {
            System.out.println("Test failed");
            System.out.println("Expected output" + expectedOutput);
            System.out.println("Actual output" + actualOutput);
        }

    public class Tally {
        public static void main(String[] args) {
            Scanner input = new Scanner(System.in);
            System.out.print("Enter the number of Votes");
            arrayList<Integer> votes = new ArrayList<Integer>();
            List<String> votes = new ArrayList<>();
            votes.add("Bush");
            votes.add("Bush");
            votes.add("Bush");
            votes.add("Shrub");
            votes.add("Hedge");
            votes.add("Shrub");
            votes.add("Bush");
            votes.add("Hedge");
            votes.add("Bush");

            String winner = tally(votes);
            System.out.println(winner + " received the most votes!");

            for (int i = 0; i < votes.size(); i++) {
                votes.add(input.nextInt());
            }
        }


    }

    }
}